#include "../../HEADERS/MCAL/GPIO.h"

void Lcd_ports_init(void)
{
    // Enable clock for GPIOA, GPIOB, GPIOE, and GPIOD
    SYSCTL_RCGCGPIO_R = SYSCTL_RCGCGPIO_R0 | SYSCTL_RCGCGPIO_R1 
    | SYSCTL_RCGCGPIO_R3 | SYSCTL_RCGCGPIO_R4;
	
    while (((SYSCTL_PRGPIO_R & SYSCTL_RCGCGPIO_R0 ) == 0)
    || ((SYSCTL_PRGPIO_R & SYSCTL_RCGCGPIO_R1 ) == 0)
    || ((SYSCTL_PRGPIO_R & SYSCTL_RCGCGPIO_R3 ) == 0)
    || ((SYSCTL_PRGPIO_R & SYSCTL_RCGCGPIO_R4 ) == 0)) {};
    
    //a5,a6,a7
	GPIO_PORTA_LOCK_R   = GPIO_LOCK_KEY;
	GPIO_PORTA_CR_R     |= (0XE0);
	GPIO_PORTA_DIR_R   |= 0XE0;
	GPIO_PORTA_DEN_R   |= 0XE0;
	GPIO_PORTA_AMSEL_R  &= ~(0XE0);
	GPIO_PORTA_AFSEL_R  &= ~(0XE0);
	GPIO_PORTA_PCTL_R   &= ~(0XE0);
	GPIO_PORTA_DATA_R  &= ~(0XE0);
    
    //b1,b0,b4,
    GPIO_PORTB_LOCK_R   = GPIO_LOCK_KEY;
	GPIO_PORTB_CR_R     |= (0X13);
	GPIO_PORTB_DIR_R   |= 0X13;
	GPIO_PORTB_DEN_R   |= 0X13;
	GPIO_PORTB_AMSEL_R  &= ~(0X13);
	GPIO_PORTB_AFSEL_R  &= ~(0X13);
	GPIO_PORTB_PCTL_R   &= ~(0X13);
	GPIO_PORTB_DATA_R  &= ~(0X13);
    
    //e5,e4
    GPIO_PORTE_LOCK_R   = GPIO_LOCK_KEY;
	GPIO_PORTE_CR_R     |= (0X30);
	GPIO_PORTE_DIR_R   |= 0X30;
	GPIO_PORTE_DEN_R   |= 0X30;
	GPIO_PORTE_AMSEL_R  &= ~(0X30);
	GPIO_PORTE_AFSEL_R  &= ~(0X30);
	GPIO_PORTE_PCTL_R   &= ~(0X30);
	GPIO_PORTE_DATA_R  &= ~(0X30);

    //d0,d1,d2
    GPIO_PORTD_LOCK_R   = GPIO_LOCK_KEY;
	GPIO_PORTD_CR_R     |= (0X07);
	GPIO_PORTD_DIR_R   |= 0X07;
	GPIO_PORTD_DEN_R   |= 0X07;
	GPIO_PORTD_AMSEL_R  &= ~(0X07);
	GPIO_PORTD_AFSEL_R  &= ~(0X07);
	GPIO_PORTD_PCTL_R   &= ~(0X07);
	GPIO_PORTD_DATA_R  &= ~(0X07);
}

void UART_GPIO_INIT(void)
{
    SET(GPIO_PORTD_AFSEL_R, Functions_D6_D7);
    SET(GPIO_PORTD_DEN_R, Functions_D6_D7);
    CLR(GPIO_PORTD_PCTL_R, Clear_PCTL_D6_D7);
    SET(GPIO_PORTD_PCTL_R, Set_PCTL_D6_D7);
    CLR(GPIO_PORTD_AMSEL_R, Functions_D6_D7);
    SET(GPIO_PORTD_DIR_R, 0x80);  // Set PD7 as output (TX) and PD6 as input (RX)
}

